//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.VSmsClassServ {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VSmsClassServ.IVSmsClassServ")]
    public interface IVSmsClassServ {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVSmsClassServ/GetList", ReplyAction="http://tempuri.org/IVSmsClassServ/GetListResponse")]
        Model.VSmsClass[] GetList(string keyword, int start, int size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVSmsClassServ/GetList", ReplyAction="http://tempuri.org/IVSmsClassServ/GetListResponse")]
        System.Threading.Tasks.Task<Model.VSmsClass[]> GetListAsync(string keyword, int start, int size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVSmsClassServ/GetListWithType", ReplyAction="http://tempuri.org/IVSmsClassServ/GetListWithTypeResponse")]
        Model.VSmsClass[] GetListWithType(string keyword, string type, int start, int size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVSmsClassServ/GetListWithType", ReplyAction="http://tempuri.org/IVSmsClassServ/GetListWithTypeResponse")]
        System.Threading.Tasks.Task<Model.VSmsClass[]> GetListWithTypeAsync(string keyword, string type, int start, int size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVSmsClassServ/GetCount", ReplyAction="http://tempuri.org/IVSmsClassServ/GetCountResponse")]
        int GetCount(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVSmsClassServ/GetCount", ReplyAction="http://tempuri.org/IVSmsClassServ/GetCountResponse")]
        System.Threading.Tasks.Task<int> GetCountAsync(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVSmsClassServ/GetCountWithType", ReplyAction="http://tempuri.org/IVSmsClassServ/GetCountWithTypeResponse")]
        int GetCountWithType(string keyword, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVSmsClassServ/GetCountWithType", ReplyAction="http://tempuri.org/IVSmsClassServ/GetCountWithTypeResponse")]
        System.Threading.Tasks.Task<int> GetCountWithTypeAsync(string keyword, string type);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVSmsClassServChannel : WebApp.VSmsClassServ.IVSmsClassServ, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VSmsClassServClient : System.ServiceModel.ClientBase<WebApp.VSmsClassServ.IVSmsClassServ>, WebApp.VSmsClassServ.IVSmsClassServ {
        
        public VSmsClassServClient() {
        }
        
        public VSmsClassServClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VSmsClassServClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VSmsClassServClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VSmsClassServClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Model.VSmsClass[] GetList(string keyword, int start, int size) {
            return base.Channel.GetList(keyword, start, size);
        }
        
        public System.Threading.Tasks.Task<Model.VSmsClass[]> GetListAsync(string keyword, int start, int size) {
            return base.Channel.GetListAsync(keyword, start, size);
        }
        
        public Model.VSmsClass[] GetListWithType(string keyword, string type, int start, int size) {
            return base.Channel.GetListWithType(keyword, type, start, size);
        }
        
        public System.Threading.Tasks.Task<Model.VSmsClass[]> GetListWithTypeAsync(string keyword, string type, int start, int size) {
            return base.Channel.GetListWithTypeAsync(keyword, type, start, size);
        }
        
        public int GetCount(string keyword) {
            return base.Channel.GetCount(keyword);
        }
        
        public System.Threading.Tasks.Task<int> GetCountAsync(string keyword) {
            return base.Channel.GetCountAsync(keyword);
        }
        
        public int GetCountWithType(string keyword, string type) {
            return base.Channel.GetCountWithType(keyword, type);
        }
        
        public System.Threading.Tasks.Task<int> GetCountWithTypeAsync(string keyword, string type) {
            return base.Channel.GetCountWithTypeAsync(keyword, type);
        }
    }
}
