//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.AutoKeyWordServ {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AutoKeyWordServ.IAutoKeyWordServ")]
    public interface IAutoKeyWordServ {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoKeyWordServ/GetList", ReplyAction="http://tempuri.org/IAutoKeyWordServ/GetListResponse")]
        System.Collections.Generic.List<Model.KeyWords> GetList(string keyword, int start, int size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoKeyWordServ/GetList", ReplyAction="http://tempuri.org/IAutoKeyWordServ/GetListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Model.KeyWords>> GetListAsync(string keyword, int start, int size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoKeyWordServ/GetCount", ReplyAction="http://tempuri.org/IAutoKeyWordServ/GetCountResponse")]
        int GetCount(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoKeyWordServ/GetCount", ReplyAction="http://tempuri.org/IAutoKeyWordServ/GetCountResponse")]
        System.Threading.Tasks.Task<int> GetCountAsync(string keyword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAutoKeyWordServChannel : WebApp.AutoKeyWordServ.IAutoKeyWordServ, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutoKeyWordServClient : System.ServiceModel.ClientBase<WebApp.AutoKeyWordServ.IAutoKeyWordServ>, WebApp.AutoKeyWordServ.IAutoKeyWordServ {
        
        public AutoKeyWordServClient() {
        }
        
        public AutoKeyWordServClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutoKeyWordServClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutoKeyWordServClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutoKeyWordServClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Model.KeyWords> GetList(string keyword, int start, int size) {
            return base.Channel.GetList(keyword, start, size);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Model.KeyWords>> GetListAsync(string keyword, int start, int size) {
            return base.Channel.GetListAsync(keyword, start, size);
        }
        
        public int GetCount(string keyword) {
            return base.Channel.GetCount(keyword);
        }
        
        public System.Threading.Tasks.Task<int> GetCountAsync(string keyword) {
            return base.Channel.GetCountAsync(keyword);
        }
    }
}
